export const L={
ru:{login:'Войти',register:'Регистрация',firstName:'Имя',lastName:'Фамилия',age:'Возраст',email:'Email',phone:'Телефон',city:'Город',tiktok:'Ник в TikTok',password:'Пароль',have:'Уже есть аккаунт? Войти',no:'Нет аккаунта? Регистрация',settings:'Настройки',save:'Сохранить',saved:'Сохранено',language:'Язык',theme:'Тема',logout:'Выйти',countdown:'Обратный отсчёт',winners:'Победители',winnersCount:'Количество победителей',start:'Запустить',months:'Месяцев',days:'Дней',hours:'Часов',minutes:'Минут',seconds:'Секунд',members:'Участники',none:'Пока никого нет',del:'Удалить',congrats:'Поздравляем!',close:'Закрыть',waiting:'Ожидание конкурса',err:'Ошибка. Проверьте данные',draw:'Розыгрыш'},
ro:{login:'Autentificare',register:'Înregistrare',firstName:'Prenume',lastName:'Nume',age:'Vârsta',email:'Email',phone:'Telefon',city:'Oraș',tiktok:'Nume TikTok',password:'Parolă',have:'Ai cont? Autentifică-te',no:'Nu ai cont? Înregistrează-te',settings:'Setări',save:'Salvează',saved:'Salvat',language:'Limbă',theme:'Temă',logout:'Ieșire',countdown:'Numărătoare inversă',winners:'Câștigători',winnersCount:'Număr de câștigători',start:'Pornește',months:'Luni',days:'Zile',hours:'Ore',minutes:'Minute',seconds:'Secunde',members:'Participanți',none:'Încă nimeni',del:'Șterge',congrats:'Felicitări!',close:'Închide',waiting:'Se așteaptă concursul',err:'Eroare. Verifică datele',draw:'Tragere'},
en:{login:'Log in',register:'Sign up',firstName:'First name',lastName:'Last name',age:'Age',email:'Email',phone:'Phone',city:'City',tiktok:'TikTok nickname',password:'Password',have:'Have an account? Log in',no:'No account? Sign up',settings:'Settings',save:'Save',saved:'Saved',language:'Language',theme:'Theme',logout:'Log out',countdown:'Countdown',winners:'Winners',winnersCount:'Number of winners',start:'Start',months:'Months',days:'Days',hours:'Hours',minutes:'Minutes',seconds:'Seconds',members:'Participants',none:'Nobody yet',del:'Delete',congrats:'Congratulations!',close:'Close',waiting:'Waiting for the contest',err:'Error. Check your data',draw:'Draw'}};
Object.assign(L.ru,{effects:'Эффекты',fxOn:'Падающие монеты',size:'Размер',amount:'Количество',deleteAll:'Удалить всех',confirmAll:'Удалить ВСЕХ участников из базы?',confirmOne:'Удалить участника из базы?',removed:'Ваш аккаунт был удалён администратором',showData:'Показать данные',hideData:'Скрыть данные',winnersTitle:'Победители',noWinners:'Участников не было',sets:{mix:'Монеты и купюры',coins:'Монеты',bills:'Купюры',clover:'Клевер',stars:'Звёзды'}});
Object.assign(L.ro,{effects:'Efecte',fxOn:'Monede care cad',size:'Mărime',amount:'Cantitate',deleteAll:'Șterge toți',confirmAll:'Ștergi TOȚI participanții din bază?',confirmOne:'Ștergi participantul din bază?',removed:'Contul tău a fost șters de administrator',showData:'Arată datele',hideData:'Ascunde datele',winnersTitle:'Câștigători',noWinners:'Nu au fost participanți',sets:{mix:'Monede și bancnote',coins:'Monede',bills:'Bancnote',clover:'Trifoi',stars:'Stele'}});
Object.assign(L.en,{effects:'Effects',fxOn:'Falling coins',size:'Size',amount:'Amount',deleteAll:'Delete all',confirmAll:'Delete ALL participants from the database?',confirmOne:'Delete this participant from the database?',removed:'Your account was removed by the admin',showData:'Show data',hideData:'Hide data',winnersTitle:'Winners',noWinners:'There were no participants',sets:{mix:'Coins & bills',coins:'Coins',bills:'Bills',clover:'Clover',stars:'Stars'}});

Object.assign(L.ru,{background:'Фон',bgHint:'Вставьте ссылку на фото из интернета или с Google Диска (доступ «Все, у кого есть ссылка»). Фон подстраивается под экран: для широких экранов — одно фото, для вертикальных (телефон) — можно другое.',bgDesktop:'Фото для ПК / широких экранов',bgMobile:'Фото для телефона (необязательно)',dim:'Затемнение',blur:'Размытие',focus:{top:'⬆ Верх',center:'⬌ Центр',bottom:'⬇ Низ'},fallTitle:'Падающие элементы',fallHint:'Каждая строка — эмодзи/символы (💵💰🪙 или $ € ₽) либо ссылка на фото (интернет или Google Диск). Можно смешивать.',fallUse:'Использовать мои элементы для всех',fxCustomNote:'Администратор задал свои падающие элементы.',bgReset:'Сбросить фон и элементы',bgResetConfirm:'Сбросить фон и падающие элементы?'});
Object.assign(L.ro,{background:'Fundal',bgHint:'Lipește un link către o poză de pe internet sau Google Drive (acces „Oricine are linkul”). Fundalul se adaptează ecranului: o poză pentru ecrane late, alta (opțional) pentru cele verticale (telefon).',bgDesktop:'Poză pentru PC / ecrane late',bgMobile:'Poză pentru telefon (opțional)',dim:'Întunecare',blur:'Estompare',focus:{top:'⬆ Sus',center:'⬌ Centru',bottom:'⬇ Jos'},fallTitle:'Elemente care cad',fallHint:'Fiecare rând — emoji/simboluri (💵💰🪙 sau $ € ₽) sau link către poză (internet sau Google Drive). Se pot combina.',fallUse:'Folosește elementele mele pentru toți',fxCustomNote:'Administratorul a setat elemente proprii care cad.',bgReset:'Resetează fundalul și elementele',bgResetConfirm:'Resetezi fundalul și elementele care cad?'});
Object.assign(L.en,{background:'Background',bgHint:'Paste a photo link from the internet or Google Drive (sharing: “Anyone with the link”). The background adapts to the screen: one photo for wide screens, another (optional) for portrait/phones.',bgDesktop:'Photo for PC / wide screens',bgMobile:'Photo for phones (optional)',dim:'Dimming',blur:'Blur',focus:{top:'⬆ Top',center:'⬌ Center',bottom:'⬇ Bottom'},fallTitle:'Falling items',fallHint:'Each line is emoji/symbols (💵💰🪙 or $ € ₽) or a photo link (internet or Google Drive). You can mix them.',fallUse:'Use my items for everyone',fxCustomNote:'The admin set custom falling items.',bgReset:'Reset background and items',bgResetConfirm:'Reset background and falling items?'});

Object.assign(L.ru,{rulesHint:'Сохранено только на этом устройстве: Firebase не разрешил запись. Откройте Firebase Console → Firestore → Rules, вставьте файл firestore.rules из проекта и нажмите Publish. Потом сохраните тему ещё раз.'});
Object.assign(L.ro,{rulesHint:'Salvat doar pe acest dispozitiv: Firebase a refuzat scrierea. Deschide Firebase Console → Firestore → Rules, lipește firestore.rules din proiect și apasă Publish. Apoi salvează din nou.'});
Object.assign(L.en,{rulesHint:'Saved on this device only: Firebase denied the write. Open Firebase Console → Firestore → Rules, paste firestore.rules from the project and click Publish. Then save again.'});

Object.assign(L.ru,{savedLocal:'Сохранено на этом устройстве. Чтобы фон видели ВСЕ: нажмите «Скачать theme.json», положите файл в папку public проекта и обновите сайт на Vercel (или опубликуйте правила Firebase и сохраните ещё раз).',savedShared:'Сохранено для всех пользователей ✓',exportTheme:'Скачать theme.json',exportHint:'Без Firebase: положите theme.json в папку public и задеплойте — фон увидят все.',fbSetup:'Firebase не настроен. В Vercel → Settings → Environment Variables добавьте переменные VITE_FB_* из файла .env и сделайте Redeploy.'});
Object.assign(L.ro,{savedLocal:'Salvat pe acest dispozitiv. Ca TOȚI să vadă fundalul: apasă „Descarcă theme.json”, pune fișierul în folderul public și actualizează site-ul pe Vercel (sau publică regulile Firebase și salvează din nou).',savedShared:'Salvat pentru toți utilizatorii ✓',exportTheme:'Descarcă theme.json',exportHint:'Fără Firebase: pune theme.json în folderul public și fă deploy — toți vor vedea fundalul.',fbSetup:'Firebase nu este configurat. În Vercel → Settings → Environment Variables adaugă variabilele VITE_FB_* din .env și fă Redeploy.'});
Object.assign(L.en,{savedLocal:'Saved on this device. For EVERYONE to see it: click “Download theme.json”, put the file into the project’s public folder and redeploy on Vercel (or publish the Firebase rules and save again).',savedShared:'Saved for all users ✓',exportTheme:'Download theme.json',exportHint:'Without Firebase: put theme.json into the public folder and deploy — everyone will see the background.',fbSetup:'Firebase is not configured. In Vercel → Settings → Environment Variables add the VITE_FB_* variables from .env and Redeploy.'});
